{% set name = "pytrends" %}
{% set version = "4.9.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytrends-{{ version }}.tar.gz
  sha256: 9228055d743b00500b4670c5078c8785436a18d79082b354f7a8e57102ea82d1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.3
  run:
    - lxml
    - pandas >=0.25
    - python >=3.3
    - requests

test:
  imports:
    - pytrends
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dreyco676/pytrends
  summary: Pseudo API for Google Trends
  license: Apache-2.0
  # license file manually packaged. See https://github.com/GeneralMills/pytrends/pull/443
  license_file: LICENSE

extra:
  recipe-maintainers:
    - IlanaRadinsky
